// Explicit Lucide icon map — generated from the names the design system uses (DESIGN.md › Iconography).
// Only these components reach the bundle (tree-shaking survives because every import is static).
// Add a name here when a ported component needs it; an unknown name is a type error in <Icon>.
// Regenerate: .tmp/scripts/icon-names.txt holds the list collected from the export.
import {
  Activity,
  AlignLeft,
  Apple,
  Archive,
  ArchiveRestore,
  ArrowDown,
  ArrowDownAZ,
  ArrowDownToLine,
  ArrowLeft,
  ArrowLeftRight,
  ArrowRight,
  ArrowRightToLine,
  ArrowUp,
  ArrowUpFromLine,
  ArrowUpNarrowWide,
  ArrowUpRight,
  AtSign,
  Ban,
  Bell,
  Bookmark,
  BookmarkPlus,
  Calendar,
  CalendarOff,
  CalendarPlus,
  ChartLine,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  CircleAlert,
  CircleCheck,
  CircleDashed,
  CircleDot,
  CircleHelp,
  CircleOff,
  CircleSlash2,
  CircleUser,
  ClipboardPaste,
  Clock,
  CloudCheck,
  CloudOff,
  CloudUpload,
  Code,
  Copy,
  CornerDownRight,
  Crown,
  Database,
  Download,
  Ellipsis,
  ExternalLink,
  Eye,
  EyeOff,
  FileCode,
  FileInput,
  FileOutput,
  FilePlus,
  FilePlus2,
  FileSearch,
  FileSearch2,
  FileText,
  FileUp,
  Filter,
  Flag,
  FlagOff,
  FlaskConical,
  Folder,
  FolderInput,
  FolderOpen,
  FolderOutput,
  Folders,
  GitBranch,
  GitMerge,
  Globe,
  GripVertical,
  Hash,
  Heading,
  History,
  Image,
  Inbox,
  Kanban,
  KeyRound,
  Keyboard,
  Leaf,
  LifeBuoy,
  Link,
  Link2,
  List,
  ListOrdered,
  Lock,
  LogIn,
  LogOut,
  Mail,
  Megaphone,
  Merge,
  MessageSquare,
  Milestone,
  MonitorDown,
  MonitorSmartphone,
  Moon,
  Package,
  Palette,
  PanelLeft,
  PanelRight,
  Paperclip,
  Pencil,
  Play,
  Plug,
  Plus,
  Printer,
  RefreshCw,
  Repeat,
  Rocket,
  Save,
  Search,
  Send,
  Settings,
  Settings2,
  Shapes,
  Share2,
  Shield,
  SmilePlus,
  Square,
  SquareArrowOutUpRight,
  SquareCheck,
  SquareCheckBig,
  Star,
  Strikethrough,
  Sun,
  Table,
  Tag,
  Tent,
  TextQuote,
  Trash2,
  Truck,
  Undo2,
  Unlink,
  Unplug,
  Upload,
  User,
  UserCog,
  UserMinus,
  UserPlus,
  UserX,
  Users,
  Warehouse,
  Wrench,
  X,
  type LucideIcon,
} from "lucide-react";

export const LUCIDE_ICONS = {
  "strikethrough": Strikethrough,
  "list-ordered": ListOrdered,
  "square-check": SquareCheck,
  "text-quote": TextQuote,
  "heading": Heading,
  "hash": Hash,
  "arrow-down-a-z": ArrowDownAZ,
  "circle-slash-2": CircleSlash2,
  "arrow-up": ArrowUp,
  "arrow-down": ArrowDown,
  "activity": Activity,
  "align-left": AlignLeft,
  "apple": Apple,
  "archive": Archive,
  "archive-restore": ArchiveRestore,
  "arrow-down-to-line": ArrowDownToLine,
  "arrow-left": ArrowLeft,
  "arrow-left-right": ArrowLeftRight,
  "arrow-right": ArrowRight,
  "arrow-right-to-line": ArrowRightToLine,
  "arrow-up-from-line": ArrowUpFromLine,
  "arrow-up-narrow-wide": ArrowUpNarrowWide,
  "arrow-up-right": ArrowUpRight,
  "at-sign": AtSign,
  "ban": Ban,
  "bell": Bell,
  "bookmark": Bookmark,
  "bookmark-plus": BookmarkPlus,
  "calendar": Calendar,
  "calendar-off": CalendarOff,
  "calendar-plus": CalendarPlus,
  "chart-line": ChartLine,
  "check": Check,
  "chevron-down": ChevronDown,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "chevron-up": ChevronUp,
  "circle": Circle,
  "circle-alert": CircleAlert,
  "circle-check": CircleCheck,
  "circle-dashed": CircleDashed,
  "circle-dot": CircleDot,
  "circle-help": CircleHelp,
  "circle-off": CircleOff,
  "circle-user": CircleUser,
  "clipboard-paste": ClipboardPaste,
  "clock": Clock,
  "cloud-check": CloudCheck,
  "cloud-off": CloudOff,
  "cloud-upload": CloudUpload,
  "code": Code,
  "copy": Copy,
  "corner-down-right": CornerDownRight,
  "crown": Crown,
  "database": Database,
  "download": Download,
  "ellipsis": Ellipsis,
  "external-link": ExternalLink,
  "eye": Eye,
  "eye-off": EyeOff,
  "file-code": FileCode,
  "file-input": FileInput,
  "file-output": FileOutput,
  "file-plus": FilePlus,
  "file-plus-2": FilePlus2,
  "file-search": FileSearch,
  "file-search-2": FileSearch2,
  "file-text": FileText,
  "file-up": FileUp,
  "filter": Filter,
  "flag": Flag,
  "flag-off": FlagOff,
  "flask-conical": FlaskConical,
  "folder": Folder,
  "folder-input": FolderInput,
  "folder-open": FolderOpen,
  "folder-output": FolderOutput,
  "folders": Folders,
  "git-branch": GitBranch,
  "git-merge": GitMerge,
  "globe": Globe,
  "grip-vertical": GripVertical,
  "history": History,
  "image": Image,
  "inbox": Inbox,
  "kanban": Kanban,
  "key-round": KeyRound,
  "keyboard": Keyboard,
  "leaf": Leaf,
  "life-buoy": LifeBuoy,
  "link": Link,
  "link-2": Link2,
  "list": List,
  "lock": Lock,
  "log-in": LogIn,
  "log-out": LogOut,
  "mail": Mail,
  "megaphone": Megaphone,
  "merge": Merge,
  "message-square": MessageSquare,
  "milestone": Milestone,
  "monitor-down": MonitorDown,
  "monitor-smartphone": MonitorSmartphone,
  "moon": Moon,
  "package": Package,
  "palette": Palette,
  "paperclip": Paperclip,
  "pencil": Pencil,
  "play": Play,
  "plug": Plug,
  "plus": Plus,
  "printer": Printer,
  "refresh-cw": RefreshCw,
  "repeat": Repeat,
  "rocket": Rocket,
  "save": Save,
  "search": Search,
  "send": Send,
  "settings": Settings,
  "settings-2": Settings2,
  "shapes": Shapes,
  "share-2": Share2,
  "shield": Shield,
  "smile-plus": SmilePlus,
  "square": Square,
  "square-arrow-out-up-right": SquareArrowOutUpRight,
  "square-check-big": SquareCheckBig,
  "star": Star,
  "sun": Sun,
  "table": Table,
  "tag": Tag,
  "tent": Tent,
  "trash-2": Trash2,
  "truck": Truck,
  "undo-2": Undo2,
  "unlink": Unlink,
  "unplug": Unplug,
  "upload": Upload,
  "user": User,
  "user-cog": UserCog,
  "user-minus": UserMinus,
  "user-plus": UserPlus,
  "user-x": UserX,
  "users": Users,
  "warehouse": Warehouse,
  "wrench": Wrench,
  "x": X,
  "panel-left": PanelLeft,
  "panel-right": PanelRight,
} as const satisfies Record<string, LucideIcon>;

export type LucideIconName = keyof typeof LUCIDE_ICONS;
